---

- name: Exercice 2
  hosts: test
  become: true

  tasks:
  - name: Création archive répertoire /etc dans /tmp/etc.tar.gz
    community.general.archive:
      path: /etc
      dest: /tmp/etc.tar.gz
      owner: root
      group: root
      mode: '444'