---

- name: Exercice 1
  hosts: test 
  become: true
  vars:
    maboucle:  "{{ range( 1 ,  9+1 ) }}"
    
  tasks:
    - name: Création de répertoire	
      ansible.builtin.file:
        path: /home{{ item }}
        state: directory
        owner: root
        group: root
        mode: '755'
      loop: "{{ maboucle }}"
 
    - name: Création répertoire auto
      ansible.builtin.file:
        path: /auto
        state: directory
        owner: root
        group: root
        mode: '755'  
    
    - name: Création liens symbolique
      ansible.builtin.file:
        src: /home{{ item }}
        dest: /auto/home{{ item }}
        owner: root
        group: root
        state: link
      loop:  "{{ maboucle }}"

