---
# tasks file for nfs_client

- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install nfs utils
  ansible.builtin.package:
    name: "{{ nfs_client_pkg }}"
    state: present
  # notify: nfs_server_start

- name: NFS service activation
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true

- name: NFS fstab et mount
  ansible.posix.mount:
    src:  "{{ nfs_client_server }}:{{ nfs_client_path }}"
    path: /mnt
    fstype: nfs
    state: mounted