---
# handlers file for nfs

- name: NFS start
  ansible.builtin.service:
    name: nfs-server
    state: started

- name: NFS restart
  ansible.builtin.service:
    name: nfs-server
    state: restarted