---
# handlers file for nfs

- name: Start nfs
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true
  listen: nfs_server_start

- name: Restart nfs
  ansible.builtin.service:
    name: nfs-server
    state: restarted
  listen: nfs_server_restart